INSERT INTO department (department_name)
VALUES 
    ("Engineering"),
    ("Finance"),
    ("Legal"),
    ("Sales");

INSERT INTO roles (fk_department_id, role_title, role_salary)
VALUES
  (4,"Sales Lead",100000),
  (4,"Salesperson",80000),
  (1,"Lead Engineer",150000),
  (1,"Software Engineer",120000),
  (2,"Account Manager",160000),
  (2,"Accountant",125000),
  (3,"Legal Team Lead",250000),
  (3,"Lawyer",190000);

INSERT INTO employee (fk_role_id, first_name, last_name)
VALUES
  (5,"Georgi","Facello"),
  (8,"Bezalel","Simmel"),
  (1,"Parto","Bamford"),
  (7,"Chirstian","Koblick"),
  (1,"Kyoichi","Maliniak"),
  (4,"Anneke","Preusig"),
  (1,"Tzvetan","Zielinski"),
  (6,"Saniya","Kalloufi"),
  (8,"Sumant","Peac"),
  (2,"Duangkaew","Piveteau"),
  (1,"Mary","Sluis"),
  (6,"Patricio","Bridgland"),
  (1,"Eberhardt","Terkki"),
  (2,"Berni","Genin"),
  (8,"Guoxiang","Nooteboom"),
  (8,"Kazuhito","Cappelletti"),
  (5,"Cristinel","Bouloucos"),
  (3,"Kazuhide","Peha"),
  (1,"Lillian","Haddadi"),
  (3,"Mayuko","Warwick"),
  (4,"Ramzi","Erde"),
  (1,"Shahaf","Famili"),
  (4,"Bojan","Montemayor"),
  (7,"Suzette","Pettey"),
  (2,"Prasadram","Heyers"),
  (1,"Yongqiao","Berztiss"),
  (3,"Divier","Reistad"),
  (8,"Domenick","Tempesti"),
  (8,"Otmar","Herbst"),
  (3,"Elvis","Demeyer"),
  (8,"Karsten","Joslin"),
  (4,"Jeong","Reistad"),
  (6,"Arif","Merlo"),
  (6,"Bader","Swan"),
  (3,"Alain","Chappelet"),
  (4,"Adamantios","Portugali"),
  (6,"Pradeep","Makrucki"),
  (5,"Huan","Lortz"),
  (7,"Alejandro","Brender"),
  (6,"Weiyi","Meriste"),
  (1,"Uri","Lenart"),
  (4,"Magy","Stamatiou"),
  (7,"Yishay","Tzvieli"),
  (7,"Mingsen","Casley"),
  (4,"Moss","Shanbhogue"),
  (4,"Lucien","Rosenbaum"),
  (2,"Zvonko","Nyanchama"),
  (7,"Florian","Syrotiuk"),
  (5,"Basil","Tramer"),
  (4,"Yinghua","Dredge");