INSERT INTO department (department_name)
VALUES 
    ("Engineering"),
    ("Finance"),
    ("Legal"),
    ("Sales");

INSERT INTO role (role_title, role_salary)
VALUES
    ("Sales Lead","100000"),
    ("Salesperson","80000"),
    ("Lead Engineer","150000"),
    ("Software Engineer","120000"),
    ("Account Manager","160000"),
    ("Accountant","125000"),
    ("Legal Team Lead","250000"),
    ("Lawyer","190000");

INSERT INTO employee (first_name, last_name)
VALUES
    ("Georgi","Facello"),
    ("Bezalel","Simmel"),
    ("Parto","Bamford"),
    ("Chirstian","Koblick"),
    ("Kyoichi","Maliniak"),
    ("Anneke","Preusig"),
    ("Tzvetan","Zielinski"),
    ("Saniya","Kalloufi"),
    ("Sumant","Peac"),
    ("Duangkaew","Piveteau"),
    ("Mary","Sluis"),
    ("Patricio","Bridgland"),
    ("Eberhardt","Terkki"),
    ("Berni","Genin"),
    ("Guoxiang","Nooteboom"),
    ("Kazuhito","Cappelletti"),
    ("Cristinel","Bouloucos"),
    ("Kazuhide","Peha"),
    ("Lillian","Haddadi"),
    ("Mayuko","Warwick"),
    ("Ramzi","Erde"),
    ("Shahaf","Famili"),
    ("Bojan","Montemayor"),
    ("Suzette","Pettey"),
    ("Prasadram","Heyers"),
    ("Yongqiao","Berztiss"),
    ("Divier","Reistad"),
    ("Domenick","Tempesti"),
    ("Otmar","Herbst"),
    ("Elvis","Demeyer"),
    ("Karsten","Joslin"),
    ("Jeong","Reistad"),
    ("Arif","Merlo"),
    ("Bader","Swan"),
    ("Alain","Chappelet"),
    ("Adamantios","Portugali"),
    ("Pradeep","Makrucki"),
    ("Huan","Lortz"),
    ("Alejandro","Brender"),
    ("Weiyi","Meriste"),
    ("Uri","Lenart"),
    ("Magy","Stamatiou"),
    ("Yishay","Tzvieli"),
    ("Mingsen","Casley"),
    ("Moss","Shanbhogue"),
    ("Lucien","Rosenbaum"),
    ("Zvonko","Nyanchama"),
    ("Florian","Syrotiuk"),
    ("Basil","Tramer"),
    ("Yinghua","Dredge");